import './globals.css'
import {
  Roboto_Flex as Roboto,
  Sansita_Swashed as Sansita,
} from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const sansita = Sansita({
  subsets: ['latin'],
  variable: '--font-sansita',
  weight: '700',
})

export const metadata = {
  title: 'Minas tem tudo de bom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.variable} ${sansita.variable} font-sans text-preto`}
      >
        {children}
      </body>
    </html>
  )
}
